'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Cinema_system_2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property __opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2018__10__EYF_Baked_Cheesy_Hot_METHOD_4_555a8033f8704211ab5307aa930c8807() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__20"& _ 
                        "18__10__EYF-Baked-Cheesy-Hot-METHOD-4-555a8033f8704211ab5307aa930c8807", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0_34000_00240_5_701_24000_097_Item_Front() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0_34000_00240_5_701_24000_097_Item_Front", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property assorted_soda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("assorted-soda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cheese_sauce_for_cheese_fries_and_nachos_hero_01_e6ccf966688c43ec8025cf9a19678423() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cheese-sauce-for-cheese-fries-and-nachos-hero-01-e6ccf966688c43ec8025cf9a19678423"& _ 
                        "", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property creed_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("creed 3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property korean_hot_dogs_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("korean-hot-dogs-6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Simply_Recipes_Perfect_Popcorn_LEAD_41_4a75a18443ae45aa96053f30a3ed0a6b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Simply-Recipes-Perfect-Popcorn-LEAD-41-4a75a18443ae45aa96053f30a3ed0a6b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x8189_jpg_pagespeed_ic_WOkQhhA81A() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x8189.jpg.pagespeed.ic.WOkQhhA81A", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x8189_jpg_pagespeed_ic1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x8189.jpg.pagespeed.ic1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x8605_jpg_pagespeed_ic_1pTvV2q_c0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x8605.jpg.pagespeed.ic.1pTvV2q-c0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x8606_jpg_pagespeed_ic_JoWTQ6Ir0L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x8606.jpg.pagespeed.ic.JoWTQ6Ir0L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
